#!/bin/bash

if [[ $# -lt 2 ]]; then
        echo "Usage: $0 srcDownloadUrl dataDestDir"
        exit 0 
fi

if [ $# -eq 2 ]; then
	dataDestDir=$2
else 
	random_flag=`cat /dev/urandom | tr -cd '0-1' | head -c 1`
	random_flag=1
	if [[ $random_flag -eq 1 ]]; then
		dataDestDir=/home/youtube
	else
		dataSrc=/Data/tmp/`cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32`
		dataDestDir=/Data/youtube
	fi
fi

dataSrc=/home/tmp/`cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32`
mkdir -p "$dataSrc" && cd "$dataSrc"

#PAFY_BACKEND="internal"
#ytdl -b "$1"

youtube-dl -f mp4 "$1"

if [[ $? -eq 0 ]]; then 
	mkdir -p "$dataDestDir"
        mv * "$dataDestDir/" 
	echo "+++$1 suc !!! +++"
else
	echo "---$1 aborted !!! ---"
fi

rm -fr "$dataSrc"
